var bayes = require("bayes")

var classifier = bayes();
var classifier = bayes();
classifier.learn("Thank using Debit Card for purchase worth Rs on POS at Projekt txn","money");
classifier.learn("code can also tap on this link to verify phone","update");
classifier.learn("Congrats GB Data days been credited to account To check balance Dial","ads");
classifier.learn("Congratulations on opening store on Remember more share more earn received as store opening bonus Check email next steps","update");
classifier.learn("successfully registered account on this device","update");
classifier.learn("tried accessing via a new device on at Please log into digibank and contact us via DIGI Virtual Assistant to report any suspected fraud","update");
classifier.learn("Happy trails and safe travels debit card is ready international use","update");
classifier.learn("Use as login OTP OTP is confidential never calls asking OTP Sharing it with anyone gives them full access to Wallet","update");
classifier.learn("We received login request from new phone at If did not attempt raise query at or call us at","update");
classifier.learn("is One Time Password online purchase of at recharge thru Bank Debit Card ending Don't share this with anyone","money");
classifier.learn("Thank for using Debit Card for purchase worth on POS at recharge txn","update");
classifier.learn("Hi As per RBI directives it is mandatory to complete KYC for Wallet by To update login to select KYC Ignore if already updated","update");
classifier.learn("A/C been debited by INR on New balance is INR To report unauthorized transaction please SMS UNAUTH to","money");
classifier.learn("A/C been credited with INR on New balance is INR","money");
classifier.learn("transaction of Rs via failed If amount been deducted it will be credited back in working days","money");
classifier.learn("Rs has been credited back to account for failed transaction on with UTR number","money");
classifier.learn("A/C been debited by INR on New balance is INR To report an unauthorized transaction please SMS UNAUTH to","money");
classifier.learn("UPI User account is debited INR on Date PM by UPI Ref NoDownload","money");
classifier.learn("UPI User a/c nois credited with INR on PM for reversal of transaction UPI Ref no","money");
classifier.learn("Please use OTP to complete transaction Please do not share this one time password with anyone else","money");
classifier.learn("Get instant help with My App Check balance validity and more on My Click","ads");
classifier.learn("is MOBILE APP Code Enter this code ONLY in the Mobile App never use this code on a website","update");
classifier.learn("added cashback in wallet for Order of Recharge of Mobile Promocode GET Upto Rs Cashback on Recharge/Pay Code FAMILY","money");
classifier.learn("Shipped Redmi A Gold GB)with order ID been shipped and will be delivered by Saturday, Feb will receive another SMS when Ekart Logisticss Wishmaster is out to deliver it Track shipment here","update");
classifier.learn("is One Time Password for online purchase thru Bank Debit Card ending Don't share this with anyone","money");
classifier.learn("Thank for using Debit Card for a purchase worth Rs on POS at txn","update");
classifier.learn("Rs credited to account of linked to on Info UPI","money");
classifier.learn("Confirmed Order for Postpartum Matern is successfully placed & will reach by Track or give missed call to","update");
classifier.learn("Customer Pepperfry or its employees will never Call/SMS/Email asking for personal bank info or to deposit money into any bank a/c for promotional rewards Beware of fraudsters and do not act on such messages Please read data security policy at","ads");
classifier.learn("sent Rs to via from bank a/c","update");
classifier.learn("is One Time Password for online purchase of Rs at thru Bank Debit Card ending Don't share this with anyone","money");
classifier.learn("Thank for using Debit Card for a purchase worth Rs on POS REECHARGE at txn","update");
classifier.learn("Received Rs from in Paytm Wallet Wallet txn id Get Rs Cashback at nearby stores","money");
classifier.learn("bank declined transfer request of Rs amount been added back to wallet wallet balance now is Rs","update");
classifier.learn("Recharge done on MRP Rs Rs GST payable by Rs Talktime RS Bal Rs TransID","update");
classifier.learn("EXTRA GB for days on First time download of TV App Click Dial to Check Balance","ads");
classifier.learn("Get instant help with My App Check balance validity and more on My App Click","ads");
classifier.learn("Use as login OTP OTP is confidential never calls asking for OTP Sharing it with anyone gives them full access to Wallet","update");
classifier.learn("OTP for transaction Aspiring Minds Assessment Pvt Ltd is Do not share it with anyone","update");
classifier.learn("Request received to send Rs to Updated Wallet Balance Rs IMPS reference number RRN","update");
classifier.learn("Thank for downloading my airtel app One Time Password(OTP) for completing registration on app is It is usable once and valid for mins from request Please do not share OTP with anyone","update");
classifier.learn("Recharge done on PM Rs GST payable by Rs TransID FULL Month Internet Dial","update");
classifier.learn("Benefit Rs recharge successful call rates are Local + STD Mobile call p/sec for days To check tariff dial EXTRA GB for days on First time download of TV App Click Dial to Check Balance","update");
classifier.learn("successfully done a PREPAID recharge for of Rs from Wallet Avl bal Rs","update");
classifier.learn("Congratulations Benefit of Local+STD mobile calls 30p/min for days been credited to account Dial for balance","update");
classifier.learn("Thanks for using","ads");
classifier.learn("Hi have successfully created a UPI virtual payment address for Bank account in for UPI transactions","update");
classifier.learn("ALERT accessed ur profile section on at If not pls change passwords immediately Download","update");
classifier.learn("Thanks for registering for Internet Banking can also use Mobile Banking App with NetBanking User ID & password","update");
classifier.learn("changed Netbanking Profile password on Feb at PM IST Do not share it with anyone Download","update");
classifier.learn("is One Time Password for online purchase of Rs at Recharge ccavenue thru Debit Card ending Don't share this with anyone","money");
classifier.learn("Thank for using Debit Card for a purchase worth Rs on POS at","update");
classifier.learn("Thank for using Debit Card for a purchase worth Rs on POS at txn","update");
classifier.learn("SORRY THIS TRANSACTION TYPE IS NOT SUPPORTED AT PRESENT","update");
classifier.learn("AC Credited INR on REVERSE POS PUR Avl Bal INR Plz download Buddy","money");
classifier.learn("Request received to send Rs to Updated Wallet Balance Rs IMPS reference number (RRN)","money");
classifier.learn("a/c no is credited by Rs on by a/c linked to mobile IMPS Ref no Download","money");
classifier.learn("added a new VPA payee Contact us via virtual assistant on app if this was not initiated by","update");
classifier.learn("added to payee list Please log into and contact us via the Virtual Assistant to report any suspected fraud","update");
classifier.learn("a/c no is credited by Rs by a/c linked to mobile IMPS Ref noDownload","money");
classifier.learn("We've transferred INR from account ending with to pay The RRN for tracking is Thank for with us","money");
classifier.learn("Received Rs from in Wallet Wallet txn id Get Rs Cashback at nearby stores","money");
classifier.learn("Alert pack benefit of Local+STD mobile is expiring today Recharge again for continued benefit For best Offers Balance dial","ads");
classifier.learn("Apply in Corpzpro Skill Development Program and add value to CV by taking up Mentor based Project","ads");
classifier.learn("Payments Bank Savings a/c is credited with Rs Txn Avl Balance Rs OFFER CASHBACK","money");
classifier.learn("Hi We Develop Mobile Applications(Android,IOS,web apps) Websites & Digital Marketing Services in Best Budgets","ads");
classifier.learn("a/c no is credited by Rs on by a/c linked to mobile (IMPS Ref no","money");
classifier.learn("Request received to send Rs to Updated Wallet Balance Rs IMPS reference number (RRN)","money");
classifier.learn("Dear UPI User account is debited INR on Date PM by UPI Ref No Download","money");
classifier.learn("As per RBI guidelines, personal & bank transfers from wallet will be suspended from To address inconvenience a one-time bank transfer without any charges is permitted till Team JioMoney","ads");
classifier.learn("As per RBI guideline can do free money transfer from Money wallet to a bank a/c till From money transfer will be available only to full KYC wallets Update min KYC on & continue enjoying our services Full KYC upgrade will be launched shortly","ads");
classifier.learn("Thank for using SBI Debit Card for a purchase worth Rs on POS at txn","update");
classifier.learn("Hi our customer contact centre number for Account customers is changing from March Kindly call our new number for any queries or issues between am to pm Mon to Sat (except holidays) Local charges apply","ads");
classifier.learn("Paytm added Rs cashback in Paytm wallet for Order of Bill Payment for TATA POWER - DDL (Promocode: TPDDL50) Upto Rs Cashback on movie tickets Code:MOVIE200","money");
classifier.learn("A/C a debit by transfer of Rs on Avl Bal Rs Download","money");
classifier.learn("Urgent reminder Dear Customer wallet will be discontinued Feb Kindly utilize the available balance of Rs in wallet by using Visa virtual debit card For any further queries please refer to FAQs","update");
classifier.learn("Use as login OTP is confidential never calls asking for OTP Sharing it with anyone gives them full access to Wallet","update");
classifier.learn("is OTP for Debit Card transaction at for INR The OTP will expire in seconds Please do not share","money");
classifier.learn("is OTP to login to Account","update");
classifier.learn("is OTP for Debit Card transaction at for INR OTP will expire in seconds Please do not share","money");
classifier.learn("Recharge done on GST payable by Rs Talktime:RS TransID FULL Month Internet! Dial","ads");
classifier.learn("Hold for INR created in AC on Download","money");
classifier.learn("OTP for Aadhaar and valid for minutes Generated at","update");
classifier.learn("Urgent reminder wallet will be discontinued Kindly utilize available balance on wallet by using Visa virtual debit card For any further queries please refer to FAQs","update");
classifier.learn("Complete KYC to use Wallet for exclusive benefits can do a one time withdrawal to bank before Feb ","ads");
classifier.learn("Hold for INR removed in AC Download","money");
classifier.learn("Get QR code for accepting payments directly in bank at charge Register as a merchant Now Click","ads");
classifier.learn("Hi PIN is Happy hiking","update");
classifier.learn("Beneficiary added successfully to Wallet for funds transfer","update");
classifier.learn("no is credited by Rs by linked to mobile PRIVATE LIMITED IMPS Ref no","money");
classifier.learn("Best Offer Rs mein payein Local aur STD call min din tak Tariff check karne ke liye dial","ads");
classifier.learn("Payments dwara bhugtan karein aur payein cashback Tata Star Bazaar ke sabhi store par Shartein laagu","ads");
classifier.learn("Websites Month Mobile Friendly Design We also Provide Services E-Commerce Online Exam Portal BULK SMS Call","ads");
classifier.learn("OTP for transaction is Do not share it with anyone","money");
classifier.learn("Thank for using Internet Banking Transaction Ref No for Rs on Feb","update");
classifier.learn("Rs credited to account of linked to on Info","money");
classifier.learn("Customer query with service request number has been closed","update");
classifier.learn("Bank will never ask to update any critical data online if received such mail pls report it immediately to report","ads");
classifier.learn("Hi As per directives it is mandatory to complete KYC for Wallet by To update login to Pockets & select KYC Ignore if already updated","ads");
classifier.learn("Airtel Payments dwara bhugtan karein aur payein FLAT Rs OFF Barista par nyuntam Rs ke bill par Shartein laagu","ads");
classifier.learn("Hey added to Kite waitlist Look out for a link on phone See soon","update");
classifier.learn("OTP for Virtual Card Generation is Do not share it with anyone","money");
classifier.learn("Hold for INR created in AC on Download","money");
classifier.learn("OTP to approve Virtual Card Transaction is Do not share it with anyone","money");
classifier.learn("Dispatched package with Postpartum Maternity After Pre will reach by Apr Track at or give missed call to","update");
classifier.learn("As per guidelines the new transaction limit on wallet is Rs per month effective All payment services continue as is","update");
classifier.learn("Hi From we a NEW Customer Contact Centre number for our Customers can call us on between Mon to Sat except holidays for any queries Local charges applicable Save the number","ads");
classifier.learn("Customer Aadhaar number successfully linked with customer ID","update");
classifier.learn("Customer query with service request number closed","update");
classifier.learn("Hold for INR removed in AC on Download","money");
classifier.learn("Candidate Result for Part 1 of the shortlisted teams of announced visit our or team qualified for grand finale Result for Part 2 of shortlisted teams of Software edition will be announced on March Regards Team SIH","update");
classifier.learn("Customer Rs Paises credited to mobile account towards Ads played on To check Rewards Tune credit dial ","money");
classifier.learn("Rs added to balance Total balance is Rs View Statement","money");
classifier.learn("Cashback of Rs added to balance To view balance visit","money");
classifier.learn("Thank for using SBI Debit Card 478XX0977 for a purchase worth Rs300.0 on POS AMAZON at AMAZON txn# LU6097346952","update");
classifier.learn("Shortlisted Teams Heartiest Congratulations Part 1 of the results were announced yesterday more teams to be announced as part of Part 2 results today Question is, what comes next We are here to answer all questions today Session by Organizing Secretary and Secretary Evaluation Committee When TODAY On FB LIVE We look forward to highly interactive participation","update");
classifier.learn("Candidate Part 1 and Part 2 of shortlisted teams of Software edition announced Please visit our website to see if team has qualified for grand finale Regards Team","update");
classifier.learn("linked to is credited with by","money");
classifier.learn("VPA linked to is debited for and the amount is credited to VPA","money");
classifier.learn("Customer account is credited with INR Current Balance is INR","money");
classifier.learn("Cashback of has been added to To view balance visit","money");
classifier.learn("Gentle Reminder Credits worth Rs will expire tonight Use them soon to order favorites","ads");
classifier.learn("Recharge done on MRP GST payable by","update");
classifier.learn("Recharge of Rs successful for Dial for balance Operator ref Refer to get Rs on Android app","update");
classifier.learn("Best Offer mein payein Local aur STD call min din tak Tariff check karne ke liye dial","ads");
classifier.learn("Customer won a brand new smartphone last month so could by simply sharing feedback of purchase on droom Click","ads");
classifier.learn("first app is ready Install it and sign in to link to PC","update");
classifier.learn("OTP for and valid for minutes Generated at","update");
classifier.learn("माननीय प्रधानमंत्री से मार्च को राष्ट्रीय पोषण मिशन का शुभारंभ करेंगे सुपोषित के इस आंदोलन में सहभागी बनें ","ads");
classifier.learn("DIRECT ADMISSION IN B.TECH AGAINST SRM GALGOTIA COLLEGE OR UNIVERSITY","ads");
classifier.learn("Alert As per guidelines update KYC with Wallet to continue enjoying the features of the wallet Click","ads");
classifier.learn("Bank verification OTP is","update");
classifier.learn("OTP One Time Password for completing registration on my app It is usable once and valid for mins Please do not share OTP with anyone","update");
classifier.learn("initiated to add Rs to account Please keep the txn id for future reference","money");
classifier.learn("One Time Password for online purchase of Rs at thru ending Don't share this with anyone","money");
classifier.learn("have initiated to add Rs to account Please keep the txn id for future reference","money");
classifier.learn("have added Rs in Bank wallet Avl Bal Rs Txn ID","money");
classifier.learn("Recharge done on payable by","update");
classifier.learn("VPA linked to is debited for and the amount is credited to VPA","money");
classifier.learn("Dear Customer Purchase transaction using card no is successful Clear Balance in is INR For lost card fraudulent transactions visit","update");
classifier.learn("Dear Customer account no is debited with INR Current Balance is INR","money");
classifier.learn("transferred Rs from bank a/c to Bank","money");
classifier.learn("VPA linked to Bank a/c no is debited for and the amount is credited to VPA ","money");
classifier.learn("is the OTP to complete internet banking transaction It is valid for minutes Please do not share with anyone","money");
classifier.learn("international usage is switched on for card ending can now use Debit Card abroad on ATMs for shopping or on international sites","update");
classifier.learn("have made a purchase for Rs on using Debit Card New balance is To report an unauthorized transaction please SMS UNAUTH to","update");
classifier.learn("Best Offer Rs mein payein Local aur STD call din tak Tariff check karne ke liye dial","ads");
classifier.learn("Customer Pepperfry or its employees will never asking for personal bank info or to deposit money into any bank for promotional rewards Beware of fraudsters and do not act on such messages Please read data security policy at","ads");
classifier.learn("Bank Savings a/c is credited with Rs Txn ID Avl Balance Rs UPGRADE OFFER CASHBACK","money");
classifier.learn("Customer Invalid debit card no Kindly use the correct debit card no and send the message again","update");
classifier.learn("Bank dwara bhugtaan karein aur payein cashback Spencer aur Hypercity store par Shartein laagu","ads");
classifier.learn("have made a purchase for Rs on Miniclip using Debit Card New balance is To report an unauthorized transaction please SMS UNAUTH to","update");
classifier.learn("विश्व उपभोक्ता अधिकार दिवस पर बधाई केंद्रीय मंत्री","ads");
classifier.learn("Customer Rs has been credited to mobile account towards Ads played on Mar To check Rewards Tune credit dial","money");
classifier.learn("otp is","update");
classifier.learn("Avoid closure of Account with just a fingerprint Give a missed call to to fix an appointment complete Full KYC of account","ads");
classifier.learn("is organising a workshop on IoT with Android on March in Delhi Automate appliances from phone app Enroll Now","ads");
classifier.learn("Avoid closure of Account with just a fingerprint Give a missed call to fix an appointment & complete Full KYC of account","ads");
classifier.learn("Confirmed Order for Easy care Hot is successfully placed & will reach by Track or give missed call to","update");
classifier.learn("Gentle Reminder Credits worth Rs will expire on Sunday Use them soon to order favorite","ads");
classifier.learn("bill for is due soon Pay instantly with Please ignore if already paid","update");
classifier.learn("has a debit by transfer of Rs Avl Bal Rs Download","money");
classifier.learn("has been added to balance Total balance is Rs View Statement ","money");
classifier.learn("Thank for recharging for on If eligible cashback will be credited within hours","update");
classifier.learn("Thank for using Debit Card for a purchase worth on POS If not done by forward this SMS from mobile number registered with SBI to block card may also call","update");
classifier.learn("payment on for using balance is successful balance is now Rs View Statement","update");
classifier.learn("Dispatched package with Easy care Hot Water Bottle will reach by Track at or give missed call to","update");
classifier.learn("We have already added Rs account Claim extra bonus by getting first order Valid until March Log In ","ads");
classifier.learn("Dear Customer never ever share Card number, expiry date CVV PIN OTP password with anyone This can be misused Bank never asks for such details","ads");
classifier.learn("Dear Customer our branches are open today from Kindly get Full KYC done by just visiting nearest branch Click to locate nearest branch ","ads");
classifier.learn("is One Time Password for online purchase of Rs at thru Debit Card ending Don't share this with anyone","money");
classifier.learn("Thank for using for a purchase worth on POS If not done by forward this SMS from mobile number registered with to block card may also call","update");
classifier.learn("credited to account of linked to Info","money");
classifier.learn("Rs has been paid to For reference wallet transaction id is Updated balance: Rs","update");
classifier.learn("Get instant zero balance bank a/c using Aadhaar & PAN number Earn higher FD interest rate & get exciting offers","ads");
classifier.learn("Arriving early Easy care Hot Water Bottle, Multicolor will be delivered by Track","update");
classifier.learn("Bank will NEVER ask to share MPIN OTP or Password Do not disclose credentials to anyone Queries Dial","ads");
classifier.learn("Arriving by package with Easy care Hot Water is on road with our and will be delivered by ","update");
classifier.learn("Delivered package with Easy care Hot Water Bottle, Multicolor More info at","update");
classifier.learn("Confirmed Order for is successfully placed & will reach by Track or give missed call ","update");
classifier.learn("Thank for using Debit Cardfor a purchase worth on POS If not done by forward this SMS from mobile number registered with to block card may also call","update");
classifier.learn("Customer Rs has been credited to mobile account towards Ads played on To check Rewards Tune credit, dial ","money");
classifier.learn("Dispatched package with Li-Polymer Power will reach by Track at or give missed call to","update");
classifier.learn("Bank se Pay karein aur payein cashback Star Bazaar ke sabhi store par Shartein laagu","ads");
classifier.learn("While at ATMs be aware about suspected on ATM slots If anything is suspected don't use card & inform bank","ads");
classifier.learn("Hi Grofers Bachat club membership expired saved additional Rs with last membership Renew membership now & buy groceries at lowest prices","ads");
classifier.learn("mobile number verification code is for confirming the cash-on-delivery order This OTP code is valid for minutes Thanks","update");
classifier.learn("Order Placed order for Rs is confirmed can check order status at","update");
classifier.learn("Arriving Today Li-Polymer Power bank 2i (Black) is out for delivery Track","update");
classifier.learn("Delivered package with Mi Li-Polymer Power bank 2i (Black) More info at","update");
classifier.learn("Prevent Air Pollution Download APP from & APP Stores Know Air Quality & Inform Polluting Activity on APP","ads");
classifier.learn("Student The last date of registration for MTRE has been extended until Don't miss out this last opportunity to avail the benefits of MTRE Register today on Regards IES","update");
classifier.learn("code","update");
classifier.learn("Hi ticket(s) for Sign up for early access to home game tickets, on onwards has been delivered Booking confirmation has been sent to Here are the ticket details Sign Up Order ID Total amount is Rs","update");
classifier.learn("Order Shipped Order has been shipped through Delhivery The tracking code is Track order at ","update");
classifier.learn("Dear Customer won a brand new smartphone last month so could by simply sharing feedback of purchase on droom Click","ads");
classifier.learn("सिर्फ़ महीना देकर गाजियाबाद मे घर खरीदे GDA aprvd CL","ads");
classifier.learn("shipment with AWB Number & Order no is out for delivery Please keep Rs cash ready Track shipment here","update");
classifier.learn("Package from with Order ID could not be delivered today by For any queries call or call us at","update");
classifier.learn("Customer Rs has been credited to mobile account towards Ads played on To check Rewards Tune credit, dial","money");
classifier.learn("Thanks for registering for DD T20 match tickets Bookings are now open on Paytm DD vs Kings XI Punjab DD vs Royal Challengers Bangalor & DD vs Kolkata Knight Rider Book & get a movie voucher worth Rs Code","update");
classifier.learn("Dynamic website at rs and e commerce website starting at rs with android application payment gateway hosting and year support call","ads");
classifier.learn("Customer has been credited to mobile account towards To check Rewards Tune credit dial","money");
classifier.learn("Introducing instant savings account that gives higher FD interest rates No min balance required Apply Instantly","ads");
classifier.learn("Now CHALO Ramlela Maidan Delhi ANNA HAZARE ANSHAN & ANDOLAN for NATION Missed Call Join Team Online Reg Team Thanks FWD&share","ads");
classifier.learn("I'm asking this last time if u want to clear ur bill then give me that right now in front of block","personal");
classifier.learn("plan ADD ON for Numbe has expired on To recharge click Dial to know current balance validity, plan details and for exciting recharge plans","update");
classifier.learn("Order Rejected Order No couldn’t be delivered and hence it has been cancelled If still want the product please place a new order on","update");
classifier.learn("Customer As per request song has been changed for Number Charges: Rs To Deactivate please call Thank Team","update");
classifier.learn("Received Rs from in Wallet Wallet txn id Flat Rs Cashback on Bus Tickets ","money");
classifier.learn("Rs credited to account of linked Info","money");
classifier.learn("दवाओं पर छूट फ्री होम डिलीवरी पर मिस्ड कॉल दें लाइफकेर","others");
classifier.learn("Thanks for registering for GATEFORUM WORKSHOP Details are Date March Venue GATEFORUM SAKET Near Saket Metro Station Gate No Reporting time PM","update");
classifier.learn("Open Zero Balance with & get Assured Cashbacks Click here to avail this offer apply","ads");
classifier.learn("UPI User account is debited INR on Date by UPI Ref NoDownload","money");
classifier.learn("have added Rs to Wallet using bank","update");
classifier.learn("Withdrawal of Rs from wallet to account has been successful Bank Reference No","update");
classifier.learn("a/c no is credited by Rs by a/c linked to mobile","money");
classifier.learn("Withdrawal of from PhonePe wallet to account has been successful Bank Reference No","update");
classifier.learn("a/c nois credited by a/c linked to mobile Download","money");
classifier.learn("A/C has been credited with INR New balance is INR","money");
classifier.learn("Thanks for registering for DD match tickets Bookings are now open for more home games in May.DD vs Rajasthan Royals DD vs Sunrisers Hyderabad DD vs Chennai Super Kings & DD vs Mumbai Indian Book now on","update");
classifier.learn("I am job-search assistant To connect with top recruiters please verify profile at Job Helpline ","ads");
classifier.learn("Welcome to Employment Exchange To call recruiters who specialize in field please click here To edit profile please go to profile All the best Employment Exchange Helpline","update");
classifier.learn("Customer request for Switching Off INTL service for card is processed successfully Reference No","update");
classifier.learn("Thank for using Debit Card for a purchase worth Rs on POS at SERVICES If not done by forward this SMS from mobile number registered with to to block card may also call","update");
classifier.learn("verification code for Live Quiz Game to Win Money Online App","update");
classifier.learn("Housefull Sale is live We've added Rs.100 to Grofers wallet Use it to pay for next order Lowest prices guaranteed Everyday Shop Now","ads");
classifier.learn("Credited INR on REVERSE POS PUR Avl Bal INR Plz download Buddy","money");
classifier.learn("have made a purchase for Rs SERVICES using Debit Card New balance To report an unauthorized transaction please SMS","money");
classifier.learn("Debited INR Transferred to A/C Balance INR","money");
classifier.learn("Received Rs from in Wallet Wallet txn id Spin the wheel & win Baaghi Coupons","money");
classifier.learn("One Time Password for online purchase thru Debit Card ending Don't share this with anyone","money");
classifier.learn("Confirmed Order for Mangat Ram Dollar Safed other items is successfully placed Track or give missed call to","update");
classifier.learn("कार्ड नम्बर सीवीवी पिन ओटीपी किसी को न बताएं बैंक कभी नहीं पूछता","ads");
classifier.learn("While receiving an international call if an Indian number or no number is displayed on phone, please inform on toll free number","ads");
classifier.learn("A/C has been credited with INR New balance is","money");
classifier.learn("'ve transferred from bank a/c to Of India","update");
classifier.learn("A/C has been debited by INR on New balance is INR To report an unauthorized transaction please SMS UNAUTH","money");
classifier.learn("Arriving Today Mangat Ram Dollar Safed Chana other items will be delivered by Track","update");
classifier.learn("Dispatched package with Mangat Ram other items will reach by Track at or give missed call to","update");
classifier.learn("INR credited to A/c No on through NEFT with UTR by neft","money");
classifier.learn("Confirmed Order for Honor 8 Pro is successfully placed & will reach by Track or give missed call to","update");
classifier.learn("Thank for using Debit Card for a purchase worth Rs on POS If not done by forward this SMS from mobile number registered with to to block card may also call","update");
classifier.learn("Arriving by package with Mangat Ram Dollar Safed Chana items is on road and will be delivered by","update");
classifier.learn("Dispatched package with tracking id has been dispatched Track at or give missed call to","update");
classifier.learn("One Time Password for online purchase thru Debit Card ending Don't share this with anyone","money");
classifier.learn("Rs has been added to balance Total balance is Rs View Statement ","money");
classifier.learn("Thank for using Debit Card for a purchase worth Rs on POS If not done by forward this SMS from mobile number registered with to to block card may also call","update");
classifier.learn("payment on for Rs using Pay balance is successful balance is now View Statement","update");
classifier.learn("Cashback of Rs has been added to Pay balance To view balance visit","money");
classifier.learn("Dispatched package with MOBSTAR Matte Screenguard for will reach by Track at or give missed call to","update");
classifier.learn("A/C has been credited with INR New balance is INR","money");
classifier.learn("Delivered package with Mangat Ram Dollar Safed Chana and other items More info at","update");
classifier.learn("आपका पैकेज रास्ते मे है और तक आपके पास पहुँच जाएगा अधिक जानकारी के लिए क्लिक करें","others");
classifier.learn("Arriving Today MOBSTAR Matte Screenguard for Huawei Honor will be delivered by","update");
classifier.learn("Delivered package with MOBSTAR Matte Screenguard for Huawei Honor More info at","update");
classifier.learn("Dispatched package with Casotec Pudding Soft TPU will reach by Track at http or give missed call to ","update");
classifier.learn("Cashback of Rs has been added to Pay balance To view balance visit","money");
classifier.learn("आपका पैकेज Casotec Pudding Soft TPU Back Case रास्ते मे है और तक आपके पास पहुँच जाएगा अधिक जानकारी के लिए क्लिक करें","others");
classifier.learn("Oye tera WiFi kyu nhi aa RHA h","personal");
classifier.learn("We could not deliver as we could not contact on the phone Re-attempt on next working day","update");
classifier.learn("Thank for contacting Did I solve problem today If Yes click If No click","update");
classifier.learn("Arriving Today package is out for delivery Track","update");
classifier.learn("Delivered package with Casotec Pudding Soft TPU Back Case Cover for Pro Black More info at","update");
classifier.learn("Arriving by Amazon package is on road and will be delivered by","update");
classifier.learn("WhatsApp code can also tap on this link to verify phone","update");
classifier.learn("verification code for Trivia","update");
classifier.learn("OTP One Time Password for completing registration on app It is usable once and valid for mins Please do not share OTP with anyone","update");
classifier.learn("Use as login OTP OTP is confidential never calls asking for OTP Sharing it with anyone gives them full access to Wallet","update");
classifier.learn("one time password to proceed on It is valid for minutes Do not share OTP with anyone","update");
classifier.learn("Delivered package was successfully delivered More info at","update");
classifier.learn("verification code please do not share this with anyone","update");
classifier.learn("SIM SWAP ALERT Airtel never calls to do a SIM Swap by sending an SMS SIM to WITHOUT having a NEW SIM Beware of such calls as it may lead to banking or financial fraud misuse of mobile number","ads");
classifier.learn("verification code is","update");
classifier.learn("mobile number and device is successfully captured for UPI registration","update");
classifier.learn("Use as login OTP OTP is confidential","update");
classifier.learn("अगर आपके पास कोई अंतरराष्ट्रीय कॉल आई है, जिसमे दर्शाया गया नंबर भारतीय है या कोई भी नंबर नहीं दर्शाया गया है तो कृप्या इसकी जानकारी टोल फ्री नंबर पर दें","ads");
classifier.learn("verification PIN","update");
classifier.learn("Customer Rs has been credited to mobile account towards Ads played on To check Rewards Tune credit dial","money");
classifier.learn("has been debited by INR on New balance is INR To report an unauthorized transaction please SMS UNAUTH to","money");
classifier.learn("User cashback points added to wallet Check points balance at","update");
classifier.learn("Thanks for being a part of the Family We have not received any referrals from till now Click to invite friends Earn Rs for each friend when they claim their first deal with a bill","ads");
classifier.learn("estatement for is ready Log into account now to view the latest statement","update");
classifier.learn("Customer or its employees will never asking for personal bank info or to deposit money into any bank a/c for promotional rewards Beware of fraudsters and do not act on such messages Please read data security policy at","ads");
classifier.learn("Use login OTP OTP is confidential never calls asking for OTP Sharing it with anyone gives them full access to Wallet","update");
classifier.learn("paid com Rs Do mobile recharge for family members get upto Rs cashback on Code FAMILY ","update");
classifier.learn("Thank for using Card for a purchase worth Rs on POS If not done by forward this SMS from mobile number registered with to to block card may also call","update");
classifier.learn("have successfully done a recharge for of Rs from Wallet Avl bal Rs","update");
classifier.learn("UPI User account is debited INR by UPI Ref No Download","money");
classifier.learn("Open Zero Balance with Bank & get Assured Cashbacks on transactions Click here to avail this offer","ads");
classifier.learn("Use as login OTP OTP is confidential never calls asking for Sharing it with anyone gives them full access to Wallet","update");
classifier.learn("One Time Password for online purchase of Rs Debit Card ending Don't share this with anyone","money");
classifier.learn("Order Placed We have received order for PC RAM It will be delivered by Thu Apr Applicable cashback will be given within hrs of shipment","update");
classifier.learn("Thank for using Debit Card for a purchase worth If not done by forward this SMS from mobile number registered with to block card may also call","update");
classifier.learn("User we have successfully validated mobile number for activating Pockets by","update");
classifier.learn("have used of daily GB high speed internet quota on Number After consumption of GB data Internet speed will be reduced in case do not have any active data plan Click to recharge with data booster and continue enjoying high speed internet Dial to know current balance, validity plan details and for exciting recharge plans","update");
classifier.learn("Gold balance is as of April Festive Offer Buy Gold at & win times extra gold every hour T&C apply","update");
classifier.learn("Shipped GB has been shipped and will reach by Thu Apr Track order and cashback status at Flat Rs Cashback on headphones pendrives & more","update");
classifier.learn("has added Rs cashback in wallet for Order of Promocode ONCEAMONTH Win Gold with times at nearby shops","money");
classifier.learn("Bank Savings a/c is credited with Rs Txn ID Avl Balance Rs OFFER CASHBACK","money");
classifier.learn("order of placed on is now expected to be delivered by","update");
classifier.learn("Delivered was successfully delivered More details at","update");
classifier.learn("replacement item for order ID is being processed by the merchant The seller will ship the item after the original item has been picked up from","update");
classifier.learn("return request RAM will be picked up by Bluedart Returns_QC post a doorstep quality check For more details on Doorstep Quality Check please check e-mail Flat Rs Cashback on headphones,pendrives & more","update");
classifier.learn("customer we will attempt pickup of return shipment from today Please keep shipment packed and ready","update");
classifier.learn("plan for no will expire on To avoid STOPPAGE of services need to recharge IMMEDIATELY Click or visit nearest Jio retailer","update");
classifier.learn("replacement item for order ID is being processed by the merchant The seller will ship the item after the original item has been picked up from","update");
classifier.learn("Refund Initiated We have successfully initiated a refund of Rs against the return request for Click for refund details","update");
classifier.learn("Hi Pockets virtual has been renewed on Please make note of the new validity date and CVV by logging into the app In case have a physical card please re-confirm address in the app and place a request for a renewed physical card","update");
classifier.learn("plan for will expire on To avoid STOPPAGE of services need to recharge IMMEDIATELY Click or visit nearest Jio retailer","update");
classifier.learn("customer or our partners will never ask for Debit Card number Expiry date Card Verification Value (CVV) One Time Password (OTP) PIN number Do not share such information with fraudsters who claim to be from Bank Income Tax department or other regulatory bodies etc","ads");
classifier.learn("Customer our branches are open today from Kindly get Full KYC done by just visiting nearest branch Click to locate nearest branch ","ads");
classifier.learn("आपके जियो नंबर के प्लान की वैधता को समाप्त हो जाएगी|सेवायें अखंडित चालू रखने के लिए आपको तुरंत रीचार्ज करने की आवश्यकता है| क्लिक करें या नज़दीकी जियो रीटेलर से संपर्क करें","update");
classifier.learn("Customer never ever share Card number, expiry password with anyone This can be misused Bank never asks for such details","ads");
classifier.learn("Update Apologies The seller Traders has cancelled the replacement item PC RAM from Order Refund of Rs has been processed Get Upto Cashback on Tyre Inflators","update");
classifier.learn("आपके के प्लान की वैधता को समाप्त हो जाएगी|सेवायें अखंडित चालू रखने के लिए आपको तुरंत रीचार्ज करने की आवश्यकता है| क्लिक करें या नज़दीकी रीटेलर से संपर्क करें","others");
classifier.learn("We are sorry that payment for failed Pls try again later","update");
classifier.learn("Customer with regards to query please call us on Our customer care is available","update");
classifier.learn("OTP One Time Password for Rewardz It is valid for minutes For security reasons, do not share this password with others","money");
classifier.learn("Simpl OTP is If there's anything wrong email","update");
classifier.learn("transaction is still in process We are yet to receive a response from the Please wait for few minutes Transaction Time Mon Seats EXCUTIVE Please check the status ","update");
classifier.learn("One Time Password for online purchase of at thru Debit Card ending Don't share this with anyone","money");
classifier.learn("Customer Card ending with is used for INR at BOOKMYSHOW Current Available balance INR","money");
classifier.learn("is One Time Password for online purchase thru Debit Card ending Don't share this with anyone","money");
classifier.learn("Thank for using Debit Card for a purchase worth on POS If not done by forward this SMS from mobile number registered with to to block card may also call","update");
classifier.learn("Payment of Rs via balance for Txn ID on is successful Updated balance Rs","money");
classifier.learn("ALERT Rs has been credited to wallet Avl Bal Rs","money");
classifier.learn("Thank for using Debit Card for a purchase worth Rs on POS at Wallet Load txn If not done by forward this SMS from mobile number registered with to to block card may also call","update");
classifier.learn("Customer Please click on the above link to get M-Ticket Just show this QR Code at the entrance Please note that ","update");
classifier.learn("OTP for Aadhaar is and is valid for minutes Generated at","update");
classifier.learn("Customer Thank for registering the nominee in ASAP account","update");
classifier.learn("Congratulations are now an Account holder Download Mobile to start using account Remember when balance exceeds Rs automatically get higher Fixed Deposit rates T&C apply","update");
classifier.learn("plan MRP Number has expired on To recharge click Dial to know current balance validity, plan details and for exciting recharge plans","update");
classifier.learn("Thank for activating Axis Mobile current transaction limit is and would be upgraded to Lakhs in the next days If suspect fraudulent activity call us at T and Cs apply","update");
classifier.learn("Welcome to account has been activated To get started activate debit card & download Mobile App from","update");
classifier.learn("Always use passphrase instead of password easy to remember and difficult to guess If the phrase is safety first the passphrase can be","ads");
classifier.learn("For more information visit Login ID Password","update");
classifier.learn("plan for has expired Data speed has been reduced & outgoing calls are barred Recharge IMMEDIATELY to resume services Click on or visit nearest retailer NOW","update");
classifier.learn("A/C has a credit by Transfer of Rs Avl Bal Rs Download","money");
classifier.learn("is confirmation code","update");
classifier.learn("customer ID linked to Account No is Good Day","update");
classifier.learn("ALERT Rs has been credited to wallet Avl Bal","money");
classifier.learn("Rs cashback for order of Rs on BookMyShow on Apr is credited as balance Visit","money");
classifier.learn("Balance in savings a/c EOD is INR Credits in a/c are subject to clearing","money");
classifier.learn("Dear UPI User account is debited INR on Date PM by UPI Ref No Download","money");
classifier.learn("verification code is Click here","update");
classifier.learn("Dear student internships in Intern with Icon are now open Application deadline is PM Apply now ","ads");
classifier.learn("cashback points added to wallet Check points balance at","update");
classifier.learn("has been debited by INR on New balance is INR To report an unauthorized transaction please SMS UNAUTH to","money");
classifier.learn("One Time Password for online purchase of Rs at thru Bank Debit Card ending Don't share this with anyone","money");
classifier.learn("Thank for using Debit Card for a purchase worth on POS at txnIf not done by forward this SMS from mobile number registered with to to block card may also call","update");
classifier.learn("Received Rs from in Wallet Wallet txn id Cashback on first shopping order","money");
classifier.learn("Rs credited to account of linked to Info","money");
classifier.learn("A/C Debited INR Transferred to A/C Balance INR","money");
classifier.learn("Avoid closure of Account with just a fingerprint Give a missed call to to fix an appointment & complete Full KYC of account","ads");
classifier.learn("Never share confidential details with anyone Bank will never ask for OTP password debit card number PIN CVV & other details","ads");
classifier.learn("Camping & Rafting Riverside Camp Just Tour packages also Available","ads");
classifier.learn("have successfully registered account on this device","update");
classifier.learn("user Premium Months Pack for will expire on Click to confirm renewal & enjoy premium subscription","update");
classifier.learn("subscription at Rs will be renewed on To cancel, Go to My Purchases Section on the latest version of","update");
classifier.learn("as per request subscription has been deactivated However can enjoy watching premium content till","update");
classifier.learn("Customer or its employees will never Call SMS Email asking for personal bank info or to deposit money into any bank a/c for promotional rewards Beware of fraudsters and do not act on such messages Please read data security policy ","ads");
classifier.learn("Balance in savings as of EOD is INR Credits in a/c are subject to clearing","money");
classifier.learn("Rs credited to account of linked to on Info","money");
classifier.learn("ID will be transferred to Limited company in Ireland link to website","update");
classifier.learn("UPI User account is debited INR on Date PM by UPI Ref Download","money");
classifier.learn("transferred Rs from bank to Bank a/c","money");
classifier.learn("has been credited with INR New balance is ","money");
classifier.learn("A/C has been debited by INR on New balance is INR To report an unauthorized transaction please SMS UNAUTH to","money");
classifier.learn("is the OTP for transaction of INR on card at on OTP valid for mins Pls do not share it with anyone","money");
classifier.learn("A/c no has been credited with Rs The A/c balance is Rs Info","money");
classifier.learn("have successfully added a/c in UPI App","update");
classifier.learn("is the OTP for transaction of INR on card at OTP valid for mins Pls do not share it with anyone","money");
classifier.learn("OTP to initiate webchat with our support team This is usable once & valid for mins from the request","update");
classifier.learn("have initiated the process of adding Bank account in UPI App","update");
classifier.learn("Hi query with reference ID pertaining to transaction ID has been raised successfully","update");
classifier.learn("A/c no has been debited by Rs The A/c balance is Rs","money");
classifier.learn("has requested money Please approve or reject the request using UPI App","update");
classifier.learn("Customer Bank Debit Card PIN for card ending has been successfully set via Mobile Banking on If not authorized by call Thank for using our service","update");
classifier.learn("transferred Rs from bank a/c to Bank a/c","money");
classifier.learn("VPA linked to LTD a/c no is credited with by UPI Ref no","money");
classifier.learn("Customer account no is credited with INR Current Balance is INR","money");
classifier.learn("tried accessing via a new device on Please log into and contact us via Virtual Assistant to report any suspected fraud","update");
classifier.learn("A/c no has been debited by Rs The A/c balance is Rs Info","money");
classifier.learn("Please use to complete transaction Please do not share this one time password with anyone else","money");
classifier.learn("successfully registered new device on Please log into and contact us via the Virtual Assistant to report any suspected fraud","update");
classifier.learn("Customer Purchase transaction using card no for INR is successful Clear Balance in A/C is INR For lost card transactions visit","money");
classifier.learn("a/c no is credited by Rs by a/c linked to mobile Download","money");
classifier.learn("Request received to send to Of India Updated Wallet Balance Rs IMPS reference number ","money");
classifier.learn("Hi have successfully set up a UPI PIN for account from LTD UPI app","update");
classifier.learn("have initiated to add Rs account Please keep the txn id for future reference","money");
classifier.learn("Customer Purchase transaction is successful Clear Balance in For lost card transactions visit","money");
classifier.learn("Rs has been added to Total balance is Rs View Statement ","money");
classifier.learn("Thank for recharging for Rs on If eligible cashback will be credited within hours","update");
classifier.learn("Cashback of Rs has been added to balance To view balance visit https","money");
classifier.learn("e-statement for Apr is ready Log into account now to view the latest statement","update");
classifier.learn("has been credited with INR New balance is INR","money");
classifier.learn("has been debited by INR New balance is INR To report an unauthorized transaction please SMS UNAUTH to","money");
classifier.learn("Customer Purchase transaction at using card no for INR on is successful Clear Balance in A/C is INR For lost card fraudulent transactions visit","money");
classifier.learn("new PIN is NEVER SHARE UR PIN WITH ANYBODY Use this PIN for redeeming ur points and for logging into","update");
classifier.learn("OTP One Time Password It is valid for minutes only Please contact Customer Care at in case haven't requested for an OTP","money");
classifier.learn("Point Gateway Private Limited Booking Done MemberShipNo Points","update");
classifier.learn("have successfully redeemed points worth Rs Auth Code is For exciting offers please","money");
classifier.learn("Thank have redeemed Reward Points worth Rs at Private Limited a More Partner Please visit for more information on earning and redeeming points","update");
classifier.learn("one time password to proceed on It is valid for minutes Do not share OTP with anyone","update");
classifier.learn("Introducing instant savings A/C that gives higher FD interest rates No min balance required Apply Instantly","ads");
classifier.learn("Dear SBI UPI User, account is debited INR 3700.0 on Date 2018-05-11 11:54:21 AM by UPI Ref No 813111913687.Download YONO @ www.yonosbi.com","money");
classifier.learn("transferred Rs from bank Bank ","money");
classifier.learn("made a purchase for Rs using New balance is To report an unauthorized transaction please SMS UNAUTH to","update");
classifier.learn("not been operated since If there are no transaction till the will be flagged as Inactive","update");
classifier.learn("Customer never ever share Card number expiry date, CVV PIN OTP password with anyone This can be misused Bank never asks for such details","ads");
classifier.learn("Fingerprint authentication is enabled for Mobile Banking on for In case of any discrepancy contact Customer Care","update");
classifier.learn("Beware of fraudulent calls asking to do SIM Swap in the name of verification do not share any OTP or send SIM new SIM number to unless have the physical SIM with This may lead to fraud misuse of mobile number","ads");
classifier.learn("Customer Now earn up to interest on as compared to regular bank account Fund for more than Rs & get special year FD rate on the amount in excess of Rs if have Rs balance get on Rs apply","ads");
classifier.learn("Customer Thank for applying for Savings Account can track application status by mentioning Application ID at Customer Care","update");
classifier.learn("Avoid closure of Account with just a fingerprint Give a missed call to fix an appointment complete Full KYC of account","ads");
classifier.learn("friend just posted on like comment on the post to show some love Like","ads");
classifier.learn("Looks like entered the wrong UPI PIN Reset UPI PIN here Click here to learn more ","update");
classifier.learn("Balance in savings as of EOD is INR Credits in are subject to clearing","money");
classifier.learn("online debit card transaction One time password is This OTP will expire in seconds","money");
classifier.learn("Wallet on is now successfully linked to If didn't initiate this activity contact support immediately","update");
classifier.learn("Now Earn Up to Interest Transfer Money to Bank from other","ads");
classifier.learn("have made a payment of Rs at from mobile no Avl Bal Rs","money");
classifier.learn("verification code","update");
classifier.learn("OTP to login to Account","update");
classifier.learn("Use as account security code","update");
classifier.learn("Someone is replacing the security info for account Not ","update");
classifier.learn("received Rs from into","money");
classifier.learn("Congratulations have made transactions against pe UPI Offer and earned Rs cashback The amount will be credited within hrs to wallet Get KYC done to receive the cashback ignore if KYC is already done","update");
classifier.learn("paid pvt ltd Rs Get exciting offers and cashback when pay with on favourite apps","update");
classifier.learn("Customer our system will be undergoing critical maintenance activity between The system will not be available for any transactions","update");
classifier.learn("Customer We have added Ltd account as a beneficiary for money transfer","update");
classifier.learn("Customer As requested we have deactivated International Usage on Debit Card no ending with To activate International Usage please login to Mobile Net banking","update");
classifier.learn("As per RBI guidelines it is mandatory to complete Full KYC of ccount within 1 year of account opening So hurry up and fix an appointment today to avoid account closure on Give a missed call to now","ads");
classifier.learn("return request for COMBO TYPE C DATA CHARGING CABLE AND OTG CONNECTOR FOR Pro has been approved It will be picked by","update");
classifier.learn("return request for COMBO TYPE C DATA CHARGING CABLE AND OTG CONNECTOR FOR has been sent to the seller The refund will be processed once the seller has received and verified the return","update");
classifier.learn("Return Request Cancelled: return request for COMBO TYPE C DATA CHARGING CABLE AND OTG CONNECTOR FOR has been cancelled by the seller Please check e-mail for more details","update");
classifier.learn("We've transfered Rs from account ending with to pay","money");
classifier.learn("Recharge of Rs for via has been successful","update");
classifier.learn("ID verification code please do not share this with anyone","update");
classifier.learn("received Rs from via into","money");
classifier.learn("received Rs cashback from into wallet for Get Cashback up to Get Cashback up to on first transactions via on a min order value of on first transactions via on website on a min order value of Current cashback gift voucher balance is","money");
classifier.learn("Dear Go to to deposit money and complete the account opening process","update");
classifier.learn("initiated the process of adding account in ybl UPI APP","update");
classifier.learn("Congratulations The KYC for CRN and account number has been completed can now enjoy the full benefits of","update");
classifier.learn("no is credited Rs by linked to virtual address","money");
classifier.learn("have Created Updated UPI MPIN for account This is valid for all UPI enabled apps","update");
classifier.learn("OTP for is and is valid for minutes Generated at","update");
classifier.learn("is Dynamic Access Code for","update");
classifier.learn("Customer CRN","update");
classifier.learn("Customer We are glad to inform that request for change of address for has been updated in our system","update");
classifier.learn("While receiving an international call if an Indian number or no number is displayed on phone please inform on toll free number","ads");
classifier.learn("ALERT Aise call se savdhaan rahein jis mein Aadhaar verification ke naam par aapse SIM swap karne ko kaha jaye Jab tak aapke paas naya SIM nahi ho kirpya koi OTP share nahi karein na hi par SIM naya SIM number bhejein Isse aapko haani ya aapke mobile number ka galat istemaal ho sakta hai","ads");
classifier.learn("sorry but transaction has been declined Please check account balance","update");
classifier.learn("is debited Rs and linked to virtual address is credited","money");
classifier.learn("no is credited Rs as a reversal of debit transaction","money");
classifier.learn("transaction of Rs via failed If the amount been deducted it will be credited back in working days","money");
classifier.learn("a/c no is credited Rs by a/c linked to virtual address","money");
classifier.learn("Recharge done on payable by To check balance validity call tariff and best recharges dial or download click","update");
classifier.learn("tried accessing via a new device on Please log into and contact us via DIGI Virtual Assistant to report any suspected fraud","update");
classifier.learn("successfully registered new device on at Please log into and contact us via the Virtual Assistant to report any suspected fraud","update");
classifier.learn("Final Call Sale Please use promocode on August to avail exclusive deal on flight ticket booking Book now","ads");
classifier.learn("customer transaction at has been declined due to insufficient fund in account","update");
classifier.learn("Txn declined as Card ending with Card Pls upgrade to an International Debit Card thru or visit Home Branch","update");
classifier.learn("AC Credited INR on Avl Bal INRPlz download","money");
classifier.learn("As per request One Time Password for Set International Usage access for is","update");
classifier.learn("transaction at Debit Card IST could not be processed due to International Txn not allowed Card not valid for international txn To enable International usage on Debit Card SMS space last digits of Debit Card no to or Please call our Hrs Customer Contact Centre at for further assistance","update");
classifier.learn("Txn of Rs made on card on IST at Combined Available balance This transaction is processed as per instructions and confirmation to the merchant","money");
classifier.learn("transferred Rs from bank Bank","money");
classifier.learn("statement for is ready Log into account now to view the latest statement","update");
classifier.learn("Customer never ever share Card number expiry date CVV PIN OTP password with anyone This can be misused Bank never asks for such details","ads");
classifier.learn("VPA linked to is credited with by","money");
classifier.learn("no has been credited with Rs The balance is Rs Info Call if in India if have not done this transaction","money");
classifier.learn("Use code to verify account on May the force be with","update");
classifier.learn("Cash-load Initiated Rs as balance from recent cash payment will be added to balance within minutes Txn ID","update");
classifier.learn("Arriving by package with is on road with our will be delivered by","update");
classifier.learn("Rider welcome to app is designed to make booking experience smooth Learn how to request an AC car in minutes here","update");
classifier.learn("confirmation code is","update");
classifier.learn("Customer has been credited to mobile account towards Ads played on Apr To check Rewards Tune credit dial","money");
classifier.learn("Cashback of Rs for order placed during Recharges Bill payments offer has been added to balance Total balance is Rs View Statement ","money");
classifier.learn("On the way package with is on time and will reach by Track at ","update");
classifier.learn("Arriving Today will be delivered by Pay Rs by Cash or Debit Credit Card Enter OTP only after getting the package Track","update");
classifier.learn("Pay Now Pay Rs for package with through paylink Click to Pay","update");
classifier.learn("Arriving Today order is out for delivery Please share the OTP with the Delivery Agent to get the package","update");
classifier.learn("Now Pay on Delivery using card netbanking at doorstep and avoid arranging for cash More details at","ads");
classifier.learn("Pay balance insufficient For Subscribe Save delivery add or set up Auto Reload at","money");
classifier.learn("Arriving Today will be delivered by Pay Rs by Cash or Debit Credit Card","update");
classifier.learn("Delivered package with More info at","update");
classifier.learn("Rs has been added to Total is Rs View Statement ","money");
classifier.learn("Cashback of Rs for order placed during Recharges Bill payments offer has been added to balance Total balance is Rs View Statement","money");
classifier.learn("Recruiting full part time Agents in ur working area u can start earning up to PM Req Pass Details call to","ads");
classifier.learn("Confirmed Order for is successfully placed will reach by Track or give missed call to","update");
classifier.learn("Delivered package with More info at","update");
classifier.learn("Arriving Today will be delivered by in a secure package Enter only after getting the package Track","update");
classifier.learn("Dispatched will be securely delivered by On the delivery day get an OTP for accepting the package Track at or give missed call to","update");
classifier.learn("Package with is being returned to us If already paid refund will be initiated once we get the package","update");
classifier.learn("unlocked merchant offers are expiring on Collect offers here","update");
classifier.learn("Arriving by on road with our will be delivered by ","update");
classifier.learn("Bill Payment Successful for Number Amount reference number If eligible cashback will be credited within","update");
classifier.learn("Arriving Today for is out for delivery Track","update");
classifier.learn("Customer is now available to take calls","update");
classifier.learn("Enjoy Unlimited All Local STD Roaming Calls data SMS daily for days Applicable for all handsets Download the App Click","ads");
classifier.learn("Refund success on Money Please contact us for details at","update");
classifier.learn("Arriving Today will be delivered by","update");
classifier.learn("Arriving by on road with our will be delivered by ","update");
classifier.learn("collected offer for would expire Order Now","update");
classifier.learn("Arriving Today is out for delivery Track","update");
classifier.learn("Arriving Today will be delivered by Pay Rs","update");
classifier.learn("Pay Now Pay Rs through paylink Click to Pay","update");
classifier.learn("Cash-load Initiated Rs as balance from recent cash payment will be added to balance within minutes Txn ID","money");
classifier.learn("Cash load Successful Rs as balance from recent cash payment was added to balance Total balance","money");
classifier.learn("Thank for recharging for Rs on If eligible cashback will be credited within hours","update");
classifier.learn("collected offer for would expire by Order Now","update");
classifier.learn("Thank for recharging for Rs on If eligible cash back will be credited within hours","update");
classifier.learn("Cashback of Rs for order placed during Recharges Bill payments offer has been added to balance Total balance is Rs Statement","money");
classifier.learn("Cashback Credited added as for on Updated Balance Statement","money");
classifier.learn("Payment of Rs via for is successful Updated Rs","money");
classifier.learn("is an easy way to pay Electricity Water Gas Telecom DTH bills Use App for bill payment through","ads");
classifier.learn("We have processed refund of Rs for txn ID on should receive the money in working days","update");
classifier.learn("Customer Refund Reference ID of value Rs has been linked to Thank ","update");
classifier.learn("order for is cancelled If have already paid refund will be initiated shortly Details","update");
classifier.learn("Refund success on Credits Please contact us for details at","update");
classifier.learn("is verification code","update");
classifier.learn("Inactive Account Manager alert account will become inactive on To stop this, sign into account at","update");
classifier.learn("Arriving Today will be delivered by Track","update");
classifier.learn("Customer Central KYC number for CRN is","update");
classifier.learn("Congrats are now successfully enrolled in program Earn points on fuel payments through wallet on Apply","update");
classifier.learn("Recurring deposit is closed The amount will be credited to account","update");
classifier.learn("Recurring deposit has been created for monthly instalment of Rs","money");
classifier.learn("has been credited with INR on New balance is INR","money");
classifier.learn("Patron today is the last day to redeem bonus points at Cinepolis Fun cinemas Book now Get additional cashback on transactions","ads");
classifier.learn("Upgrading wallet to KYC wallet or Bank account is FREE Please call on to select preference By selecting an option agree to become a full KYC customer of and accept bank","ads");
classifier.learn("Use as login OTP OTP is confidential Paytm never calls asking for OTP Sharing it with anyone gives them full access to Wallet","update");
classifier.learn("Here are bonus points worth Rs Visit Cinepolis Fun Cinema to redeem Valid till Jan Get additional cashback on transactions","ads");
classifier.learn("no has been debited by Rs on The A/c balance is Rs Info GST on Charge","money");
classifier.learn("has been debited by Rs The A/c balance is Rs Info Charges for ","money");
classifier.learn("Up To Rs Off On Favourite USED CAR Models Lowest Interest Rate Of Hurry Limited Period Offer Call","ads");
classifier.learn("New Regulation empowers TV consumer for what view Contact TV Service Provider and exercise option","ads");
classifier.learn("Customer To safeguard online transactions effective debit limit on for UPI will be Rs per txn and Rs per day","update");
classifier.learn("order from is on its way Enjoy meal See order summary here","update");
classifier.learn("New Regulation empowers TV consumer Pay for what view Contact TV Service Provider and exercise option","ads");
classifier.learn("Upgrading wallet to KYC wallet account is FREE Please call on to select preference By selecting an option agree to become a full KYC customer of and accept bank","ads");
classifier.learn("By sharing code with agent I agree to submit request for upgrading my wallet limit I agree to become a full KYC customer of accept conditions listed at","update");
classifier.learn("Rs paid to Wallet txn id","money");
classifier.learn("Hi has been credited with Rs The Available Balance is Rs","money");
classifier.learn("Up To Rs Off On USED Bikes Lowest Interest Rate Of Only Anniversary Sale Visit Call Now","ads");
classifier.learn("Customer as per guidelines to avoid closure of account need to complete KYC immediately at nearest bank branch Kindly carry recent photograph PAN Card & valid KYC document with For valid KYC document list click","ads");
classifier.learn("Here golden investment opportunity Buy Gold Bonds at a discounted rate of per gm here Enjoy tax-free capital gains after years TCA","ads");
classifier.learn("paid Rs to via from bank account","money");
classifier.learn("Standing Instruction of for beneficiary on is due on","money");
classifier.learn("transaction at using Debit Card on IST could not be processed due to Insufficient account balance Combined balance is is Rs Kindly fund the account or retry transaction with an amount lesser than the combined balance","update");
classifier.learn("is credited by a/c linked to virtual address","money");
classifier.learn("Thank for using Debit Card for Rs at on Available balance in is Rs","money");
classifier.learn("a few steps away from making first investment with App Complete KYC & start investment journey","ads");
classifier.learn("Rs has been credited back to account for the failed transaction on with UTR number","money");
classifier.learn("Hi Special Offer for Download APP earn points on To optout SMS OPTOUT to","ads");
classifier.learn("OTP is Please validate the OTP to continue","update");
classifier.learn("PIN FOR PAYBACK CARD NUMBER HAS BEEN UPDATED SUCCESSFULLY","update");
classifier.learn("ALERTprofile has been updated as per request For assistance please call contact centre at","update");
classifier.learn("Credits worth Rs will expire soon as they are valid for days only Use it to order favorites Order","ads");
classifier.learn("OTP is Verify account India biggest grocery sale is here Get full cashback on any order during the","update");
classifier.learn("Get Lifetime Free credit card with great benefits only from Chip Credit Card Apply now","ads");
classifier.learn("Thank for using Debit Card for Rs at on Available balance in","money");
classifier.learn("Standing Instruction for INR from to beneficiary account No has been processed successfully on","money");
classifier.learn("payment of Rs for is successful Service provider takes working days to consider bill paid in their account","update");
classifier.learn("order from has been confirmed View order summary here","update");
classifier.learn("our valet tried reaching Kindly reach back at","update");
classifier.learn("Outgoing service on no stops on In case of no recharge Rs will deduct on from Main Bal for validity To recharge dial","update");
classifier.learn("Recharge Code purchase of Rs via has been successful","update");
classifier.learn("Rs recharge code To redeem Instruction","update");
classifier.learn("UPI User account is debited INR on Date PM by UPI Ref No Download","money");
classifier.learn("have paid Rs via at  on Ref No For queries call","money");
classifier.learn("Rs transferred to at Jan Transaction ID Updated Balance Rs","money");
classifier.learn("has a debit by transfer of  on Avl Bal","money");
classifier.learn("membership is under process and we will notify shortly once it is activated","update");
classifier.learn("there account balance is now below Rs Would like to top it up now","ads");
classifier.learn("bill for Rs is due soon instantly with Exciting offers available for Please ignore if already paid","ads");
classifier.learn("Shipped with order has been shipped and will be delivered  by Sunday Jan will receive another SMS when the Wishmaster from Logistics is out to deliver it Track shipment here","update");
classifier.learn("been credited with INR on New balance is INR For raising a dispute Please call","money");
classifier.learn("Congratulations have been shortlisted for the recruitment process with  Solutions Details mailed at Register by Register yourself for the profile at","update");
classifier.learn("Outgoing services on stops today If no recharge Rs will deduct on from main balance for day validity For Unlimited Smart Pack,dial","update");
classifier.learn("on presents upto off on travel-bags limited period offer shop now apply","ads");
classifier.learn("Rs has been credited back to account for the failed transaction on with UTR number","money");
classifier.learn("Please use OTP to complete transaction Please do not share this one time password with anyone else","money");
classifier.learn("Documents received for KYC verification Please schedule agent appointment to complete in person verification ","update");
classifier.learn("Hi KYC verification with was rejected due to incorrect details submitted Please resubmit correct details","update");
classifier.learn("a few steps away from making  first investment with App Complete KYC & start","ads");
classifier.learn("Congrats are now KYC verified with for mutual fund investments Start investing from today","update");
classifier.learn("As per Guidelines subsequent credits in low  will be disabled from However can continue to use balance and also transact through cards & net banking on the app To use balance click","update");
classifier.learn("have successfully set a new password for account Please use the new password to login into account","update");
classifier.learn("Here is a delicious cure for food swings Use code & get off next  order, TCA. Order now","ads");
classifier.learn("been credited with INR on New balance is INR For raising a dispute Please call ","money");
classifier.learn("Delivery Reminder order has been packed and will be delivered by Regards Team","update");
classifier.learn("restriction on savings account has been removed. Continue to use benefits of  savings account Queries  Write to us at","update");
classifier.learn("order Punjabi Bagh has been delivered","update");
classifier.learn("Debited INR Transferred to Balance INR","money");
classifier.learn("Reminder are ready to make first investment with us So why delay when can invest today Start investing now","ads");
classifier.learn("Get exclusive Day offers over and above existing store offers Add  before search word SmartSearch only for today","ads");
classifier.learn("Arriving Today will be delivered by Track","update");
classifier.learn("Refresh style with John Jacobs Use exclusive code for Off on eyewear Click","ads");
classifier.learn("wishes all the best for GATE Carry Admit card & valid photo ID Visit for Answer Key & Solutions","update");
classifier.learn("plans Order in Get off on next orders Use code Max discount Order till Feb  on Click Here","ads");
classifier.learn("Investing in Mutual Funds just got easier Start investing in a flash authorize us to submit personal KYC details to the KYC registration agency by clicking on this link","ads");
classifier.learn("interview for Software Developer  is scheduled with Pvt Ltd on Date Tuesday February  at Venue STONE Delhi-Meerut Rd Ghaziabad Uttar Pradesh ID Carry admit card sent on or show this SMS to interviewer","update");
classifier.learn("One Time Password for online purchase of Rs at thru Debit Card ending Don't share this with anyone","money");
classifier.learn("for using Debit Card for a purchase worth on at txn If not done by forward this SMS from mobile number registered with to to block card may also call","money");
classifier.learn("order from has been confirmed View order summary here","update");
classifier.learn("Loan approval in minutes Get up to Rs Lakh instantly on No collateral required Check approved amount  http","ads");
classifier.learn("It is DEALicious to save on food Tap on the Uber Eats app & indulge in our DEALicious Selections starting at Rs only TCA Order now","ads");
classifier.learn("A deal on every meal Flat off upto Rs on top restaurants Order from Feast Away selection on","ads");
classifier.learn("Ur Domain Expires On  SAVE MORE with LIFETIME OFF on Hosting Renewal Call Visit","update");
classifier.learn("Hi are ready to make first investment with us Start an SIP with as little as Rs per month","ads");
classifier.learn(" Ur Domain Expires On SAVE MORE with LIFETIME OFF on Hosting Renewal Call Visit","update");
classifier.learn("payment on for Rs using balance is successful balance is now Rs View Statement","money");
classifier.learn("Dispatched Delivery will reach by Track at or give missed call","update");
classifier.learn("Investing in Mutual Funds just got easier Start investing in a flash authorize us to submit personal KYC details to the MF KYC registration agency by clicking on this link","ads");
classifier.learn("Get VEHICLE INSURANCE Policy Renewal on DROOM  Fast, Easy & Secure Save Up To Visit  Call","ads");
classifier.learn("Standing Instruction of amount on Account has failed","update");
classifier.learn("been credited with INR on New balance is INR","money");
classifier.learn("Customer account no is credited with INR Current Balance is","money");
classifier.learn("This Valentine's DontSwipeRight Just give a missed call on or register on n stand a chance to WIN FREE wardrobe from CALL NOW","ads");
classifier.learn("Arriving early will be delivered today Track","update");
classifier.learn("Customer Purchase transaction at using card no for INR  is successful Clear Balance in A/C  is INR For lost card unauthorized transactions SMS HOTLIST  at","update");
classifier.learn("Rs has been added to wallet Updated balance is Rs","update");
classifier.learn("is OTP to login to Account It  valid for minutes Please do not share this with anyone","update");
classifier.learn("OTP to login to Account It is valid for minutes Please do not share this with anyone","update");
classifier.learn("paid Rs Add money now to order quickly next time Download app ","money");
classifier.learn("Rs has been added as cashback to wallet by Updated Balance is Check out our offers","money");
classifier.learn("order has been accepted by and will be delivered by Feb pm","update");
classifier.learn("is OTP to login to Account It is valid for minutes Please do not share this with anyone","update");
classifier.learn("is the OTP for Card transaction at for INR The OTP will expire in seconds Please do not share","money");
classifier.learn("Customer Purchase transaction at using card  for INR on is successful Clear Balance in A/C  is INR For lost card unauthorized transactions SMS HOTLIST at","money");
classifier.learn("paid Rs via at  Add money now to order quickly next time Download app now","money");
classifier.learn("Get FLAT Rs Cashback On Brand New  Lowest Interest Rate Of Valentine Special Offer Visit Call","ads");
classifier.learn("Candidate has been shortlisted for HR Recruiter profile Pure Day Shift Job Loc West Delhi Call or me on","update");
classifier.learn("Know what is in the Budget for us BudgetForNewIndia","ads");
classifier.learn("receiving notifications to help stay connected with friends Reply stop to turn them off","ads");
classifier.learn("want kids to start studying early to score well Can the same logic be applied for their investments Click here to know more Mutual Fund Investments are subject to market risks read all scheme related documents carefully Regards","ads");
classifier.learn("Dear welcome to For the complete To unsubscribe UNSUB to","ads");
classifier.learn("Did Know UPES offers Professional Specializations for its MBA Programs Apply Now to avail Exciting Scholarships","ads");
classifier.learn("Welcome to Haryana Enjoy Free Incoming and Outgoing calls anywhere in India while roaming nationally Kindly enable Data Roaming to use data services Data & SMS benefits will be as per plan","ads");
classifier.learn("Welcome to Jio-UP & Uttarakhand. Enjoy Free Incoming and Outgoing calls anywhere in India while roaming nationally. Kindly enable Data Roaming to use data services. 4G Data & SMS benefits will be as per your plan.","ads");
classifier.learn("Get up to Credits when refer  friends Refer them to  gift them free rides for a week Know More Refer Now","ads");
classifier.learn("is the OTP to login to Account It is valid for minutes","update");
classifier.learn("User we have successfully validated mobile number for activating by Bank","update");
classifier.learn("Greetings from Regular earning needs regular work Lets work towards achieving your goals Source a Customer now","ads");
classifier.learn("Candidate Please be informed that should not wear jackets dress containing heavy metallic buttons on test day Socks without any pockets shall be allowed inside the test lab will be asked to remove shoes outside the test lab","update");
classifier.learn("Awesome just saved Rs on with first exclusive deal of Unbox all benefits by visiting","update");
classifier.learn("Hi Wallet has been credited with Cash use them during checkout when shop for favourite meaty bites","update");
classifier.learn("Congratulations Diwali Surprise Offers are Valid Now Click Here to Check your Offers Thanks","update");
classifier.learn("Awesome  just saved Rs with first exclusive deal of Unbox all benefits by visiting","update");
classifier.learn("Congratulations SUPER membership has been enabled by can now activate SUPER for Re","update");
classifier.learn("have selected a new ATM PIN for credit card ending If have not requested it please contact us immediately","update");
classifier.learn("Customer beware of fraudulent calls sms emails offering rewards like cars holiday packages free products etc on behalf of and asking to make advance payment to receive such rewards All our offers are available only on and our App","ads");
classifier.learn("I have accidentally sent rs kindly please return","personal");
classifier.learn("has been debited with high electricity bills Now save upto  on bills by getting AC Serviced Book now on","ads");
classifier.learn("Sorry had to cancel order because some items are unavailable Please try another restaurant","update");
classifier.learn("Parents Bursting of crackers in or around school premises is strictly prohibited Any student found in possession of crackers or using them will face serious consequences Please ensure ward does not indulge in the same Pitampura Delhi","update");
classifier.learn("Its time to jingle folks Grab the best Christmas Deals at the hottest restaurants cashback only on Explore NOW","ads");
classifier.learn("Having a colorful Holi Day Make it flavorful too by celebrating with festive favorites at the best restaurants Book now","ads");
classifier.learn(" welcome to Bank have successfully opened savings account with us For queries visit","update");
classifier.learn("Call me when are free its regarding internship","personal");
classifier.learn("Woah order was delivered lightning fast in under mins Bon Appetit can now use  favourite UPI App to pay on","update");
classifier.learn("BEST WISHES to for exams We are expect excellent result If face any problem during after exams CALL","update");
classifier.learn("Hurry Few Seats left Apply now for at International Collaborations with Top global universities Know More","ads");
classifier.learn("Parents Students of Classe will observe half day on Saturday  Nov Buses ply back at am Pitampura, Delhi","update");
classifier.learn("Join the Swachh Bharat Mission and keep surroundings clean and Swachh Always use a toilet","ads");
classifier.learn("Gentle Reminder Faasos Credits worth Rs will expire tonight Use them soon to order favorites","ads");
classifier.learn("Candidate Thank for registering for Last few hours left for application to submit without any late fees Please complete the application by paying the applicable fees online Kindly ignore if already paid Thank you","update");
classifier.learn("Last  days left Flat Off on your favorite Beverages Open vouchers  more Buy now","ads");
classifier.learn("Hey free trial for is now activated and is valid till Unbox all the privileges by visiting","update");
classifier.learn("EXTRA Rs Off For Use it to grab those Styles  Brands LOVE Shop Now HURRY","ads");
classifier.learn("EVERYTHING at OFF on Footwear  Handbags at extended for TODAY Rush to nearest  now Don't miss it","ads");
classifier.learn("never calls asking for OTP Sharing this gives them full access to Wallet confidential Login OTP is","update");
classifier.learn("Thanks for giving an opportunity to Service product Send  if Dissatisfied,send  if satisfied to Premium SMS charges apply","update");
classifier.learn("EXTRA Rs For Use it to grab those Styles  Brands LOVE Shop Now HURRY","ads");
classifier.learn("Last few days left to apply for MBA Admissions Pune Scholarships up to Lakhs Highest CTC LPA APPLY NOW","ads");
classifier.learn("wallet is blocked due to no transactions or no KYC update Login Settings Update KYC to update Call to activate","update");
classifier.learn("The bike of dreams is waiting for Play the Bike Quiz here and grab right now","ads");
classifier.learn("Candidates Greetings We thank for registering for Please complete application by paying applicable fees online by November to avoid any late fees Kindly ignore if already paid Thank","update");
classifier.learn("Sorry had to cancel order because no one's available to deliver it Please try another restaurant","update");
classifier.learn("order is succesfully placed Order ID","update");
classifier.learn("Enter the code on the website CODE For security reasons this code will expire in minutes Msg and data rates may apply","update");
classifier.learn("Candidates Greetings We thank for registering for Please complete application by paying applicable fees online by November to avoid any late fees Kindly ignore if already paid Thank","update");
classifier.learn("Thank for choosing Apollo Sugar Clinics & Aashirvaad Sugar Release Control Atta Diabetes Control Offer will get a call from our Diabetes Experts shortly","ads");
classifier.learn("FREE Gift this International days left Shop & get Home Mini Shopping To optout sms OPTOUT to","update");
classifier.learn("Hey free trial is going to expire in  days Just pay Rs now to continue enjoying the benefits for a year Buy here","update");
classifier.learn("EVERYTHING at OFF on Sports Shoes Sports Apparel & Backpacks at extended for TODAY Rush to nearest now Don't miss it","ads");
classifier.learn("UPDATE eligible for a Pre-approved Insta Jumbo Loan on credit card For details visit Jumbo Loan","ads");
classifier.learn("User As per the recent update from our banking partners Instant Bank Deposit feature has been temporarily disabled Please DONOT send funds to the instant bank account until further updates from us can still add funds via Regular Bank Transfer method or using Payment Gateway actively working on resolving the issue at the earliest Inconvenience is regretted Cheers","ads");
classifier.learn("Congratulations Won have killed bill by INR We will deposit INR into credit card in the next hours","update");
classifier.learn("Thank for registering for The Great We will get in touch with soon for the pick up of xchange items","update");
classifier.learn("mobile number is linked to  account","update");
classifier.learn("MBA Admissions OPEN  Excellent PLACEMENTS with Top RECRUITERS  Apply NOW","ads");
classifier.learn("merchandise has been delivered Thank for patronage We look forward to welcome  back in our store","update");
classifier.learn("payment for the Booking ID has started Don't worry payment would be safe with us and in case of an issues we would update payment status within next mins We have also launched our fully powered chat service to resolve any queries related to this booking Please click here to chat with us","update");
classifier.learn("Good Evening gifts received by people today Create a feed to start getting gifts","ads");
classifier.learn("For Policy No with us The easier are to contact the easier it is to send important policy updates and benefits We still don’t have additional contact  email ID To update details just need to click here apply","update");
classifier.learn("all good things come with a price tag free trial has expired Just pay Rs now to continue enjoying the benefits for a year Buy here","update");

module.exports ={
	classifier : function(){
		return classifier;
	},
};